# Site settings
title: Griechenland
client:
  name: Ein Kosmos voller Sehnsuchtsorte
  link: "http://www.visitgreece.gr/"
core-se-link: https://www.secretescapes.de/aktuelle-angebote
description: >
  Malerische Inselwelten, antike Kulturschätze, pittoreske Tavernen – die Heimat der Götter ist seit jeher ein Garant für mediterrane Sternstunden.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/ch/griechenland-2019" # the subpath of your site, e.g. /blog/
img:     "/ch/griechenland-2019/_assets/img"
css:     "/ch/griechenland-2019/_assets/css"
js:      "/ch/griechenland-2019/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
